import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SWRProvider } from "./swr-provider";
import Nav from "@/components/nav";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  title: {
    template: "%s | AI in X Clone",
    default: "AI in X Clone",
  },
  description: "I'm in!",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // layout 은 SC 여야 하기에, SWRProvider를 CC 로 만들어서 가져옴
    <SWRProvider>
      <html lang="en">
        <body className={inter.className}>
          {children}
          <Nav />
        </body>
      </html>
    </SWRProvider>
  );
}
