import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SWRProvider } from "./swr-provider";
import Nav from "@/components/nav";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  title: {
    template: "%s | AI in X Clone",
    default: "AI in X Clone",
  },
  description: "I'm in!",
};

export default function RootLayout({
  children,
}: // test,
Readonly<{
  children: React.ReactNode;
  // test: React.ReactNode;
}>) {
  return (
    // layout 은 SC 여야 하기에, SWRProvider를 CC 로 만들어서 가져옴
    <SWRProvider>
      <html lang="en">
        <body
          className={`${inter.className} min-h-screen max-w-screen-sm mx-auto border-x border-gray-200 box-content`}
        >
          {/* {test} */}
          {children}
          {/* <Nav /> */}
        </body>
      </html>
    </SWRProvider>
  );
}
